# Generated by Django 5.0.6 on 2024-05-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='aumigos',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='Whatsapp do tutor'),
        ),
    ]
