# Generated by Django 5.0.6 on 2024-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aumigos',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='idade',
            field=models.IntegerField(blank=True, verbose_name='Idade do aumigo'),
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=255, verbose_name='Porte do aumigo'),
        ),
    ]
