# Generated by Django 5.0.6 on 2024-05-11 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0002_remove_aumigos_descricao_alter_aumigos_idade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aumigos',
            name='idade',
        ),
        migrations.AddField(
            model_name='aumigos',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='foto',
            field=models.ImageField(upload_to='./fotos/', verbose_name='Foto do aumigo'),
        ),
    ]
