# Generated by Django 5.0.6 on 2024-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0003_remove_aumigos_idade_aumigos_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aumigos',
            name='localidade',
            field=models.CharField(default='Não informado', max_length=255, verbose_name='Localidade do aumigo [mais especifico que cidade]'),
        ),
    ]
