# Generated by Django 5.0.6 on 2024-05-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0004_aumigos_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aumigos',
            name='foto',
            field=models.ImageField(upload_to='fotos/', verbose_name='Foto do aumigo'),
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='porte',
            field=models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], max_length=255, verbose_name='Porte do aumigo'),
        ),
    ]
