# Generated by Django 5.0.6 on 2024-05-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0005_alter_aumigos_foto_alter_aumigos_porte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AumigosFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_aumigos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='aumigos',
            name='foto',
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='localidade',
            field=models.CharField(max_length=255, verbose_name='Localidade do aumigo [mais especifico que cidade]'),
        ),
        migrations.AlterField(
            model_name='aumigos',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do aumigo(a)'),
        ),
        migrations.AddField(
            model_name='aumigos',
            name='foto',
            field=models.ManyToManyField(to='aumigos.aumigosfotos'),
        ),
    ]
