# Generated by Django 5.0.6 on 2024-05-12 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0007_photo_delete_aumigosfotos_alter_aumigos_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='foto',
        ),
        migrations.AlterField(
            model_name='photo',
            name='aumigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='aumigos.aumigos', verbose_name='foto'),
        ),
    ]
