# Generated by Django 5.0.6 on 2024-05-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0009_remove_aumigos_foto_foto_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
