# Generated by Django 5.0.6 on 2024-05-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aumigos', '0010_delete_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
                ('aumigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aumigos', to='aumigos.aumigos', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ('pk',),
            },
        ),
    ]
